### ISSUE TITLE
Fr language strings should not be here.

### ISSUE THREAD

**Issue by germanvaleroelizondo** [Palumdo/moodle-mod_teamup#4]
Fr language strings should not be here.

These fr strings have already been submitted to the french language pack maintainers and they have been accepted (https://lang.moodle.org/local/amos/contrib.php?id=28841) . 

You can now safely delete the fr language strings from GitHub and the Moodle plugins database.

Please see https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings

**Comment by Palumdo** [comment]
Thanks you. I do not know that. I do it now !

**Comment by germanvaleroelizondo** [comment]
Thank you for a nice Moodle plugin.
