### ISSUE TITLE
Hardcoded table name

### ISSUE THREAD

**Issue by Kemmotar83** [Palumdo/moodle-mod_teamup#5]
Hi,

in the file lib.php (row 269) the table name mdl_user is hard coded and causes an error with table prefixes different from the standard one.

Thanks,
Giorgio

**Comment by Palumdo** [comment]
Hi,

thank you very much. I'll corrected asap (I mean today !).

Dominique.

**Comment by Palumdo** [comment]
The table name was corrected.
